// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_403.tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/HeaderModeButton.tsx";

const manifest = {
  routes: {
    "./routes/_403.tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/HeaderModeButton.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
